### PR TITLE
Delete Readme.md

### PR DESCRIPTION
**Pull request by thkirby**
Deleted all the Readme.md content

### CODE REVIEW

**Comment by hannahheflin** [comment]
done

**Comment by Bryanj101** [comment]
testing bad pull request

**Review by Bryanj101 — CHANGES_REQUESTED** [review]
readme content deleted, restore it

**Review by hannahheflin — COMMENTED** [review]
Cool

**Review by bjproxy — CHANGES_REQUESTED** [review]
please don't delete #4

**Review by thkirby — COMMENTED** [review]
I got rid of all the changes

**Pull request merged**
